// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCKYLMe1_GcJB1aMW6ulTzZLrmDWcyhY4',
    appId: '1:39831135432:android:12ae5b8ebf8138b003f1fd',
    messagingSenderId: '39831135432',
    projectId: 'nod-try',
    storageBucket: 'nod-try.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_oa1AVis46MEUEFCzbCtY02Z1FJVnhgY',
    appId: '1:39831135432:ios:689fb8a2e7413ad303f1fd',
    messagingSenderId: '39831135432',
    projectId: 'nod-try',
    storageBucket: 'nod-try.firebasestorage.app',
    iosClientId:
        '39831135432-sbq2shm7qj0893b5a8o9nb76pv16mdpa.apps.googleusercontent.com',
    iosBundleId: 'com.devho.nodtry.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1IcuLktEeIrMZiNGIzpJnx8iJK6sJDgA',
    appId: '1:39831135432:web:788f6255cf75219503f1fd',
    messagingSenderId: '39831135432',
    projectId: 'nod-try',
    authDomain: 'nod-try.firebaseapp.com',
    storageBucket: 'nod-try.firebasestorage.app',
    measurementId: 'G-N8VXK87PYJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_oa1AVis46MEUEFCzbCtY02Z1FJVnhgY',
    appId: '1:39831135432:ios:95e15365da684b6703f1fd',
    messagingSenderId: '39831135432',
    projectId: 'nod-try',
    storageBucket: 'nod-try.firebasestorage.app',
    iosClientId:
        '39831135432-6gr4710ej4qtj317cjipn9ghg439l05h.apps.googleusercontent.com',
    iosBundleId: 'com.mindgardener.mindGardener',
  );
}
