desc "Build and upload Android (internal) + iOS (beta) simultaneously"
lane :deploy_all do
  # Build sequentially (Flutter single process)
  sh("cd .. && flutter build appbundle --release")
  sh("cd .. && flutter build ipa --release --export-options-plist=ios/ExportOptions.plist")

  # Upload in parallel
  threads = []
  threads << Thread.new do
    sh("cd ../android && bundle exec fastlane internal")
  end
  threads << Thread.new do
    sh("cd ../ios && bundle exec fastlane beta")
  end
  threads.each(&:join)
end

desc "Build and upload Android (production) + iOS (release) simultaneously"
lane :release_all do
  sh("cd .. && flutter build appbundle --release")
  sh("cd .. && flutter build ipa --release --export-options-plist=ios/ExportOptions.plist")

  threads = []
  threads << Thread.new do
    sh("cd ../android && bundle exec fastlane production")
  end
  threads << Thread.new do
    sh("cd ../ios && bundle exec fastlane release")
  end
  threads.each(&:join)
end

desc "Upload only (skip build) - Android internal + iOS beta"
lane :upload_all do
  threads = []
  threads << Thread.new do
    sh("cd ../android && bundle exec fastlane internal")
  end
  threads << Thread.new do
    sh("cd ../ios && bundle exec fastlane beta")
  end
  threads.each(&:join)
end
