default_platform(:android)

platform :android do
  desc "Submit a new build to the Internal Test Track"
  lane :internal do
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      release_status: 'draft',
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true
    )
  end

  desc "Submit a new build to Production"
  lane :production do
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      release_status: 'completed',
      skip_upload_screenshots: true,
      skip_upload_images: true
    )
  end
end
